<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL7CVe7P\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL7CVe7P/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL7CVe7P.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL7CVe7P\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerL7CVe7P\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'L7CVe7P',
    'container.build_id' => '173b15ac',
    'container.build_time' => 1517954118,
));
